# Generated by Django 4.1.3 on 2022-11-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="BlogIndexPage", new_name="LessonIndexPage",),
    ]
