# Generated by Django 4.1.3 on 2022-11-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0007_lessontagindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonpage",
            name="author",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
