# Generated by Django 4.1.3 on 2022-11-22 20:21

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0010_lessonpage_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("url", models.CharField(max_length=250)),
                ("description", wagtail.fields.RichTextField(blank=True)),
            ],
        ),
    ]
