# Generated by Django 4.1.3 on 2022-11-22 20:54

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0011_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonpage",
            name="videos",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="lesson.video"
            ),
        ),
    ]
